version: "3.7"

services:
  mysql:
    image: mysql
    command: --lower_case_table_names=1
    container_name: mysql_docker2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"  
